/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inpongopi;

/**
 *
 * @author ThinkPad
 */
public class C_klasik extends javax.swing.JFrame {

    /**
     * Creates new form C_klasik
     */
    public C_klasik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        luckyCat = new javax.swing.JLabel();
        yamalu = new javax.swing.JLabel();
        qordiHQ = new javax.swing.JLabel();
        kozi = new javax.swing.JLabel();
        twinHouse = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        luckyCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/K_luckycatt.png"))); // NOI18N
        getContentPane().add(luckyCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 170, 220, 310));

        yamalu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/K_yamalu.png"))); // NOI18N
        getContentPane().add(yamalu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 220, 310));

        qordiHQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/K_gordiHQ.png"))); // NOI18N
        getContentPane().add(qordiHQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 220, 310));

        kozi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/K_kozi.png"))); // NOI18N
        getContentPane().add(kozi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 220, 310));

        twinHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/K_twinHouse.png"))); // NOI18N
        getContentPane().add(twinHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 220, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/C_klasik.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_klasik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_klasik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_klasik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_klasik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_klasik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kozi;
    private javax.swing.JLabel luckyCat;
    private javax.swing.JLabel qordiHQ;
    private javax.swing.JLabel twinHouse;
    private javax.swing.JLabel yamalu;
    // End of variables declaration//GEN-END:variables
}
