/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inpongopi;

/**
 *
 * @author ThinkPad
 */
public class C_modern extends javax.swing.JFrame {

    /**
     * Creates new form C_modern
     */
    public C_modern() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sukukatakopi = new javax.swing.JLabel();
        lamoenanCafe = new javax.swing.JLabel();
        kopiKenangan = new javax.swing.JLabel();
        kopitagram = new javax.swing.JLabel();
        kina = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sukukatakopi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/M_suku kata kopi.png"))); // NOI18N
        sukukatakopi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sukukatakopiMouseClicked(evt);
            }
        });
        getContentPane().add(sukukatakopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 160, 220, 320));

        lamoenanCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/M_lamoenan cafe.png"))); // NOI18N
        lamoenanCafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lamoenanCafeMouseClicked(evt);
            }
        });
        getContentPane().add(lamoenanCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 220, 320));

        kopiKenangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/M_kopken.png"))); // NOI18N
        kopiKenangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kopiKenanganMouseClicked(evt);
            }
        });
        getContentPane().add(kopiKenangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 220, 310));

        kopitagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/M_kopitagram.png"))); // NOI18N
        kopitagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kopitagramMouseClicked(evt);
            }
        });
        getContentPane().add(kopitagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 220, 320));

        kina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/M_kina.png"))); // NOI18N
        kina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kinaMouseClicked(evt);
            }
        });
        getContentPane().add(kina, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 220, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_cafe/C_modern.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sukukatakopiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sukukatakopiMouseClicked
        // TODO add your handling code here:
        FC_sukuKataKopi sk = new FC_sukuKataKopi();
        sk.setLocationRelativeTo(null);
        sk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sukukatakopiMouseClicked

    private void lamoenanCafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lamoenanCafeMouseClicked
        // TODO add your handling code here:
        FC_lamoenanCaffe lc = new FC_lamoenanCaffe();
        lc.setLocationRelativeTo(null);
        lc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lamoenanCafeMouseClicked

    private void kopiKenanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kopiKenanganMouseClicked
        // TODO add your handling code here:
        FC_kopiKenangan kp = new FC_kopiKenangan();
        kp.setLocationRelativeTo(null);
        kp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kopiKenanganMouseClicked

    private void kopitagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kopitagramMouseClicked
        // TODO add your handling code here:
        FC_Kopitagram kt = new FC_Kopitagram();
        kt.setLocationRelativeTo(null);
        kt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kopitagramMouseClicked

    private void kinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kinaMouseClicked
        // TODO add your handling code here:
        FC_KinaCafe kc = new FC_KinaCafe();
        kc.setLocationRelativeTo(null);
        kc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kinaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_modern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_modern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_modern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_modern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_modern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kina;
    private javax.swing.JLabel kopiKenangan;
    private javax.swing.JLabel kopitagram;
    private javax.swing.JLabel lamoenanCafe;
    private javax.swing.JLabel sukukatakopi;
    // End of variables declaration//GEN-END:variables
}
