/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inpongopi;

/**
 *
 * @author ThinkPad
 */
public class FCaffe extends javax.swing.JFrame {

    /**
     * Creates new form FCaffe
     */
    public FCaffe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Industrial = new javax.swing.JLabel();
        btn_Klasik = new javax.swing.JLabel();
        btn_Modern = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        Jlatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Industrial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_all/Cindustrial.png"))); // NOI18N
        btn_Industrial.setText("jLabel2");
        btn_Industrial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_IndustrialMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Industrial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 300, 400));

        btn_Klasik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_all/Cklasik.png"))); // NOI18N
        btn_Klasik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_KlasikMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Klasik, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 270, 410));

        btn_Modern.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_all/Cmodern.png"))); // NOI18N
        btn_Modern.setText("jLabel4");
        btn_Modern.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ModernMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Modern, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 290, 410));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_all/back.png"))); // NOI18N
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 270, 150));

        Jlatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_all/nuansa_cafe.png"))); // NOI18N
        getContentPane().add(Jlatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 960, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        tipe t = new tipe();
        t.setLocationRelativeTo(null);
        t.setVisible(true);
        this.setVisible(false);
        System.out.println("Warkop form berhasil");
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_IndustrialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IndustrialMouseClicked
        // TODO add your handling code here:
        C_industrial cin = new C_industrial();
        cin.setLocationRelativeTo(null);
        cin.setVisible(true);
        this.setVisible(false);
        System.out.println("Warkop form berhasil");
    }//GEN-LAST:event_btn_IndustrialMouseClicked

    private void btn_KlasikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_KlasikMouseClicked
        // TODO add your handling code here:
        C_klasik ckl = new C_klasik();
        ckl.setLocationRelativeTo(null);
        ckl.setVisible(true);
        this.setVisible(false);
        System.out.println("Warkop form berhasil");
    }//GEN-LAST:event_btn_KlasikMouseClicked

    private void btn_ModernMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModernMouseClicked
        // TODO add your handling code here:
        C_modern cm = new C_modern();
        cm.setLocationRelativeTo(null);
        cm.setVisible(true);
        this.setVisible(false);
        System.out.println("Warkop form berhasil");
    }//GEN-LAST:event_btn_ModernMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCaffe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCaffe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCaffe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCaffe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCaffe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlatar;
    public javax.swing.JLabel btn_Industrial;
    private javax.swing.JLabel btn_Klasik;
    private javax.swing.JLabel btn_Modern;
    private javax.swing.JLabel btn_back;
    // End of variables declaration//GEN-END:variables
}
