/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inpongopi;

/**
 *
 * @author ThinkPad
 */
public class W_klasik extends javax.swing.JFrame {

    /**
     * Creates new form W_klasik
     */
    public W_klasik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPuaKale = new javax.swing.JLabel();
        btnKita = new javax.swing.JLabel();
        btnGhendhis = new javax.swing.JLabel();
        btnNasiKucing = new javax.swing.JLabel();
        btnBlokM = new javax.swing.JLabel();
        latar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPuaKale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/K_puaKale.png"))); // NOI18N
        btnPuaKale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPuaKaleMouseClicked(evt);
            }
        });
        getContentPane().add(btnPuaKale, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 170, 230, 310));

        btnKita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/K_Kita.png"))); // NOI18N
        btnKita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKitaMouseClicked(evt);
            }
        });
        getContentPane().add(btnKita, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 240, 310));

        btnGhendhis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/K_ghendisJawi.png"))); // NOI18N
        btnGhendhis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGhendhisMouseClicked(evt);
            }
        });
        getContentPane().add(btnGhendhis, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 220, 300));

        btnNasiKucing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/K_nasiKuning.png"))); // NOI18N
        btnNasiKucing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNasiKucingMouseClicked(evt);
            }
        });
        getContentPane().add(btnNasiKucing, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 240, 310));

        btnBlokM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/K_square.png"))); // NOI18N
        btnBlokM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBlokMMouseClicked(evt);
            }
        });
        getContentPane().add(btnBlokM, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 210, 310));

        latar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/W_klasik.png"))); // NOI18N
        getContentPane().add(latar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPuaKaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPuaKaleMouseClicked
        // TODO add your handling code here:
        FW_puaKale pk = new FW_puaKale();
        pk.setLocationRelativeTo(null);
        pk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPuaKaleMouseClicked

    private void btnKitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKitaMouseClicked
        // TODO add your handling code here:
        FW_kita k = new FW_kita();
        k.setLocationRelativeTo(null);
        k.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKitaMouseClicked

    private void btnGhendhisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGhendhisMouseClicked
        // TODO add your handling code here:
        FW_ghendisJawi g = new FW_ghendisJawi();
        g.setLocationRelativeTo(null);
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGhendhisMouseClicked

    private void btnNasiKucingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNasiKucingMouseClicked
        // TODO add your handling code here:
        FW_NasiKucing nk = new FW_NasiKucing();
        nk.setLocationRelativeTo(null);
        nk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNasiKucingMouseClicked

    private void btnBlokMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBlokMMouseClicked
        // TODO add your handling code here:
        FW_blokM bm = new FW_blokM();
        bm.setLocationRelativeTo(null);
        bm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBlokMMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(W_klasik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(W_klasik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(W_klasik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(W_klasik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new W_klasik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBlokM;
    private javax.swing.JLabel btnGhendhis;
    private javax.swing.JLabel btnKita;
    private javax.swing.JLabel btnNasiKucing;
    private javax.swing.JLabel btnPuaKale;
    private javax.swing.JLabel latar;
    // End of variables declaration//GEN-END:variables
}
