/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inpongopi;

/**
 *
 * @author ThinkPad
 */
public class W_modern extends javax.swing.JFrame {

    /**
     * Creates new form W_modern
     */
    public W_modern() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnroemahWarkop = new javax.swing.JLabel();
        btndjajaAbadi = new javax.swing.JLabel();
        btnbukitDaun = new javax.swing.JLabel();
        btnabdulMajid = new javax.swing.JLabel();
        btnKemayu = new javax.swing.JLabel();
        latar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnroemahWarkop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/M_roemahWarkop.png"))); // NOI18N
        getContentPane().add(btnroemahWarkop, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 170, 230, 310));

        btndjajaAbadi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/M_djajaAbadi.png"))); // NOI18N
        getContentPane().add(btndjajaAbadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 230, 310));

        btnbukitDaun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/M_bukitDaun.png"))); // NOI18N
        getContentPane().add(btnbukitDaun, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 230, 310));

        btnabdulMajid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/M_abdulMajid.png"))); // NOI18N
        getContentPane().add(btnabdulMajid, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 230, 310));

        btnKemayu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/M_kemayu.png"))); // NOI18N
        getContentPane().add(btnKemayu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 230, 310));

        latar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_warkop/W_modern.png"))); // NOI18N
        getContentPane().add(latar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(W_modern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(W_modern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(W_modern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(W_modern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new W_modern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnKemayu;
    private javax.swing.JLabel btnabdulMajid;
    private javax.swing.JLabel btnbukitDaun;
    private javax.swing.JLabel btndjajaAbadi;
    private javax.swing.JLabel btnroemahWarkop;
    private javax.swing.JLabel latar;
    // End of variables declaration//GEN-END:variables
}
